### ISSUE TITLE
HTTP error during search

### ISSUE THREAD

**Issue by gaarsmu** [arrrlo/Google-Images-Search#78]
Hi there, 

I am getting "HTTP error" during image search, it usually appears in the middle of the search process and it seems to be request specifications depended. API downloads some images and throws an error in the middle of the process. For example it throws an error for set of parameters:
 ```
_search_params = {
    'q': 'COVID-19',
    'num': 20,
    'safe': 'off',
    'fileType': 'jpg',
    'imgSize': 'MEDIUM',
}
```

Full error log:

```
HttpError                                 Traceback (most recent call last)
<ipython-input-4-f508988bf31b> in <module>
----> 1 gis.search(search_params=_search_params, path_to_dir='./Images_try/') #, path_to_dir='./Images_try/'

~/.conda/envs/tf2/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py in search(self, search_params, path_to_dir, width, height, custom_image_name, cache_discovery)
    119             self._search_params['num'] = num
    120 
--> 121             self._search_images(*self._get_data())
    122 
    123             if len(self._search_result) >= self._number_of_images or self.zero_return:

~/.conda/envs/tf2/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py in _search_images(self, search_params, path_to_dir, width, height, cache_discovery)
    144         i = 0
    145         threads = []
--> 146         for url in self._google_custom_search.search(
    147             search_params, cache_discovery
    148         ):

~/.conda/envs/tf2/lib/python3.8/site-packages/google_images_search/google_api.py in search(self, params, cache_discovery)
     76 
     77         search_params = self._search_params(params)
---> 78         res = self._query_google_api(search_params, cache_discovery)
     79 
     80         results = res.get('items', [])

~/.conda/envs/tf2/lib/python3.8/site-packages/google_images_search/google_api.py in _query_google_api(self, search_params, cache_discovery)
     44                                        cache_discovery=cache_discovery)
     45 
---> 46         return self._google_build.cse().list(
     47             cx=self._custom_search_cx, **search_params).execute()
     48 

~/.conda/envs/tf2/lib/python3.8/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~/.conda/envs/tf2/lib/python3.8/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    905             callback(resp)
    906         if resp.status >= 300:
--> 907             raise HttpError(resp, content, uri=self.uri)
    908         return self.postproc(resp, content)
    909 

HttpError: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?cx={my id}f&q=COVID-19&searchType=image&num=20&start=11&imgSize=MEDIUM&fileType=jpg&safe=off&key={my key}&alt=json returned "Request contains an invalid argument.">
```

Following the link doesn't help much, it says:

{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

Looking for error causes in the Internet I found that people have similar problems with other Google APIs but their solutions didn't help.

I am using GIS version 1.3.3 and python version 3.8.3.

Thank you!

**Comment by arrrlo** [comment]
Hi @gaarsmu, thank you for reporting this.
It is fixed now.
Check new version, 1.3.4

**Comment by jrmbr** [comment]
Hey, ,I still face the exact same issue with GIS 1.3.3 and python 3.7.3 and your pavckage version 1.3.4. Any idea why ?

**Comment by gaarsmu** [comment]
Hi @arrrlo,

I have updated the API to the new version and don't experience the issue any more, tried it for a few requests of various sizes. Thanks a lot!

P.S. Sorry for the late reply, I have spent last week being sick, having headaches and guessing if I have the virus or not...

**Comment by arrrlo** [comment]
> Hi @arrrlo,
> 
> I have updated the API to the new version and don't experience the issue any more, tried it for a few requests of various sizes. Thanks a lot!
> 
> P.S. Sorry for the late reply, I have spent last week being sick, having headaches and guessing if I have the virus or not...

Great to hear that it's working for you.
No problem for the late reply. Stay safe.

**Comment by arrrlo** [comment]
> Hey @arrrlo ,I still face the exact same issue with python 3.7.3 and your package version 1.3.4. Any idea why ?

I don't know. It's working fine now.
Can you paste the whole traceback here?

**Comment by jrmbr** [comment]
So sorry for the delay, I did not have access to my computer the last few days.

When I try a simple:

from google_images_search import GoogleImagesSearch
gis = GoogleImagesSearch({keys},validate_images=True)
gis.search({'q':"Test"},path_to_dir="C:/Users/Me/Desktop")

I get the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\fetch_resize_save.py", line 121, in search
    self._search_images(*self._get_data())
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\fetch_resize_save.py", line 147, in _search_images
    search_params, cache_discovery
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\google_api.py", line 78, in search
    res = self._query_google_api(search_params, cache_discovery)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\google_api.py", line 47, in _query_google_api
    cx=self._custom_search_cx, **search_params).execute()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googleapiclient\http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?cx={mycx}&q=Test&searchType=image&num=1&start=1&safe=off&key={mykey}&alt=json returned "Request contains an invalid argument.">

I uninstalled and installed v1.3.4 to be sure but no improvement... 
It is working fine on my personal computer, but when installing it on a new one it is not anymore...

Thanks for you help anyway !

**Comment by jrmbr** [comment]
Ok my bad, I made a mistake copying my cx_key... Sosorry to have bothered you ! Thanks again for the great package !

**Comment by igiul667** [comment]
Yeah, i thought the CX was the project ID. It is the search engine code you get from the search engine config page. Hope this helps
